/* Generated by scripts/gen-audio.py — do not edit by hand.
   Maps recipe id -> clip key -> text hash. Presence of a key means audio/<id>/<key>.mp3 exists. */
window.AUDIO = {
 "chicken-curry": {
  "name": "04514b211ea9",
  "step-0": "1839b3fee1b3",
  "step-1": "574cf000380e",
  "step-2": "df73a00b4caa",
  "step-3": "43edf595d1ce",
  "step-4": "25ad16f751e2",
  "step-5": "39bf1edf502f",
  "step-6": "36f8fbee771a",
  "step-7": "fd8f2ae2963d"
 },
 "tomato-chicken": {
  "name": "35ad92a68123",
  "step-0": "80e8108fa2c8",
  "step-1": "b6d9a4ad93b6",
  "step-2": "7f99bf8c9f3c",
  "step-3": "bc13e8f238f6",
  "step-4": "fd4d39431655"
 },
 "garlic-chicken-potatoes": {
  "name": "cdf2373ab151",
  "step-0": "453a91d343a5",
  "step-1": "97cc05bf85bb",
  "step-2": "786af053fb2e",
  "step-3": "6b6b66c9c579",
  "step-4": "18b586f94584",
  "step-5": "576120607352"
 },
 "yogurt-potato-salad": {
  "name": "0a5a9b67d62d",
  "step-0": "02fafd4318d0",
  "step-1": "af00a6e8e365",
  "step-2": "47de345f8f2d",
  "step-3": "e0e4c5fbf9c7",
  "step-4": "37b62d641789"
 },
 "tikka-masala": {
  "name": "1e14d90b88b1",
  "step-0": "05c1b3cfbe80",
  "step-1": "81726b69d6d3",
  "step-2": "e65b843c7e0f",
  "step-3": "fecc353c4cce",
  "step-4": "67e4d5473ad4",
  "step-5": "c0f070a1fab1",
  "step-6": "df0349f7c038",
  "step-7": "ea067c88740b",
  "step-8": "4801a0f6c3a4"
 },
 "pad-thai": {
  "name": "3666b2f3f13d",
  "step-0": "998af91920f4",
  "step-1": "9034bc029c0b",
  "step-2": "9af35e2cf854",
  "step-3": "89546cfadf4d",
  "step-4": "81643d34bc91",
  "step-5": "19be8756284b"
 },
 "tomato-chicken-pasta": {
  "name": "482731343655",
  "step-0": "d5a526c18461",
  "step-1": "870a0c81ed3e",
  "step-2": "38696f01663f",
  "step-3": "3197789ee6c0",
  "step-4": "bd6b33d86cdb",
  "step-5": "b5ce18e3d9fa",
  "step-6": "192a4e62bfa5"
 },
 "chicken-dosa": {
  "name": "4d988da1bc3d",
  "step-0": "1e9a268253ea",
  "step-1": "ea97d3855c70",
  "step-2": "ad702102238f",
  "step-3": "219604ea0cbb",
  "step-4": "3b5838de839a",
  "step-5": "9e335c2b60e8",
  "step-6": "bb50640ba843"
 },
 "basil-chicken": {
  "name": "e7462aeca655",
  "step-0": "550e63ae02e9",
  "step-1": "d6fb50f06f12",
  "step-2": "c9d6bdde6f54",
  "step-3": "e89d896c2027",
  "step-4": "24c95eb4dc46"
 },
 "sriracha-chicken": {
  "name": "36e91be1e771",
  "step-0": "9fefdf7482ec",
  "step-1": "6ecf5f4cb3e2",
  "step-2": "a8dea56795f0",
  "step-3": "3170f1bb4349",
  "step-4": "b37e0e0dff18"
 },
 "steamed-fish": {
  "name": "c345ba1de064",
  "step-0": "5ac38322c261",
  "step-1": "c7ce2f3cbbf2",
  "step-2": "c775bb6a22da",
  "step-3": "ca841ab225af",
  "step-4": "e8a4cc66ad50",
  "step-5": "af883109b789",
  "step-6": "8f794f7217f9",
  "step-7": "ce8eb16ff8a0",
  "step-8": "68b1ec8a3d8b",
  "step-9": "23f692cb6cef"
 },
 "biryani": {
  "name": "4f082799a5bb",
  "step-0": "b033f5ba781f",
  "step-1": "f4078336d2b2",
  "step-2": "effad6582c66",
  "step-3": "d095f777c5c4",
  "step-4": "c94cb27f240b",
  "step-5": "223798def2c6"
 },
 "rajma-chawal": {
  "name": "2b7fb83ae67f",
  "step-0": "5ef5feff0234",
  "step-1": "31755c065ddc",
  "step-2": "e9782d2c788b",
  "step-3": "c15917e46d12",
  "step-4": "586ece932888",
  "step-5": "9c9dce7c2bbb",
  "step-6": "75e08d258a6a",
  "step-7": "f913010ff7cf"
 },
 "channe-roti": {
  "name": "5526742bdb1c",
  "step-0": "c0d6982b9d43",
  "step-1": "d0082d961802",
  "step-2": "ee7c0bcd5490",
  "step-3": "d514317b4606",
  "step-4": "638c16e82e6a",
  "step-5": "7fffed22b9b1",
  "step-6": "edc8a1fa929b",
  "step-7": "3005a8d9da54"
 }
};
