#!/usr/bin/env python3
"""
Generate Hindi audio for every recipe with Sarvam AI's Bulbul text-to-speech,
so the site can play studio-quality voice instead of the phone's built-in voice.

Usage
  export SARVAM_API_KEY=...            # or put the key in .sarvam_key (git-ignored)
  python3 scripts/gen-audio.py                 # generate whatever is missing or changed
  python3 scripts/gen-audio.py --dry-run       # show what would be generated + char count
  python3 scripts/gen-audio.py --recipe biryani
  python3 scripts/gen-audio.py --force         # regenerate everything
  python3 scripts/gen-audio.py --speaker anushka --model bulbul:v2

What it does
  1. Evaluates js/data.js with macOS JavaScriptCore (osascript) to get the recipes as JSON.
     (No Node needed. On Linux, install node and swap eval_data_js() for a node one-liner.)
  2. For each recipe builds one clip per: recipe name, each ingredient (qty + name), each step.
     Hindi only for now — the `hi` strings.
  3. Skips clips whose text hash is unchanged (tracked in audio/manifest.js).
  4. Writes audio/<recipe-id>/{name,ing-N,step-N}.mp3 and audio/manifest.js, which the
     web app reads (window.AUDIO) to know which clips exist.

Only standard library is used.
"""
import argparse, base64, hashlib, json, os, subprocess, sys, time, urllib.request, urllib.error

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA_JS = os.path.join(ROOT, "js", "data.js")
AUDIO_DIR = os.path.join(ROOT, "audio")
MANIFEST = os.path.join(AUDIO_DIR, "manifest.js")
API_URL = "https://api.sarvam.ai/text-to-speech"

DEFAULT_MODEL = "bulbul:v3"   # bulbul:v2 was deprecated by Sarvam (Sep 2026)
DEFAULT_SPEAKER = "priya"     # female, bulbul:v3. Other v3 female voices: ritu, neha, pooja, simran, kavya
DEFAULT_PACE = 0.9            # a touch slower than normal — these are cooking instructions
LANG = "hi-IN"


def eval_data_js():
    """Run js/data.js in JavaScriptCore and return window.MENU as a Python dict."""
    jxa = (
        'ObjC.import("Foundation");'
        f'var s=$.NSString.stringWithContentsOfFileEncodingError({json.dumps(DATA_JS)},4,null).js;'
        'var window={}; eval(s); JSON.stringify(window.MENU)'
    )
    out = subprocess.run(["osascript", "-l", "JavaScript", "-e", jxa], capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit("Could not evaluate js/data.js:\n" + out.stderr)
    return json.loads(out.stdout)


def load_manifest():
    if not os.path.exists(MANIFEST):
        return {}
    with open(MANIFEST, encoding="utf-8") as f:
        txt = f.read()
    start, end = txt.find("{"), txt.rfind("}")
    return json.loads(txt[start:end + 1]) if start >= 0 else {}


def save_manifest(m):
    os.makedirs(AUDIO_DIR, exist_ok=True)
    with open(MANIFEST, "w", encoding="utf-8") as f:
        f.write("/* Generated by scripts/gen-audio.py — do not edit by hand.\n"
                "   Maps recipe id -> clip key -> text hash. Presence of a key means audio/<id>/<key>.mp3 exists. */\n")
        f.write("window.AUDIO = " + json.dumps(m, ensure_ascii=False, indent=1) + ";\n")


def clips_for(recipe):
    """Yield (key, hindi_text) for one recipe."""
    yield "name", recipe["name"]["hi"]
    for i, ing in enumerate(recipe["ingredients"]):
        if "group" in ing:
            continue
        yield f"ing-{i}", f'{ing["qty"]["hi"]} {ing["name"]["hi"]}'
    for i, step in enumerate(recipe["steps"]):
        yield f"step-{i}", step["hi"]


def text_hash(text, model, speaker, pace):
    return hashlib.sha1(f"{model}|{speaker}|{pace}|{text}".encode("utf-8")).hexdigest()[:12]


def get_key():
    key = os.environ.get("SARVAM_API_KEY")
    if not key:
        p = os.path.join(ROOT, ".sarvam_key")
        if os.path.exists(p):
            key = open(p, encoding="utf-8").read().strip()
    if not key:
        sys.exit("No API key. Set SARVAM_API_KEY or create .sarvam_key in the project root (it is git-ignored).")
    return key


def synthesize(text, key, model, speaker, pace):
    body = {
        "text": text,
        "language_code": LANG,
        "model": model,
        "speaker": speaker,
        "pace": pace,
        "speech_sample_rate": 22050,
        "output_audio_codec": "mp3",
        "enable_preprocessing": True,
    }
    req = urllib.request.Request(
        API_URL, data=json.dumps(body).encode("utf-8"),
        headers={"Content-Type": "application/json", "api-subscription-key": key}, method="POST")
    for attempt in range(5):
        try:
            with urllib.request.urlopen(req, timeout=60) as r:
                data = json.loads(r.read().decode("utf-8"))
            return base64.b64decode(data["audios"][0])
        except urllib.error.HTTPError as e:
            msg = e.read().decode("utf-8", "replace")
            if e.code in (429, 500, 502, 503) and attempt < 4:
                wait = 2 ** attempt
                print(f"    HTTP {e.code}, retrying in {wait}s…")
                time.sleep(wait)
                continue
            sys.exit(f"Sarvam API error {e.code}: {msg}")
    raise RuntimeError("unreachable")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--dry-run", action="store_true", help="list clips to generate; no API calls")
    ap.add_argument("--force", action="store_true", help="regenerate even if unchanged")
    ap.add_argument("--recipe", help="only this recipe id")
    ap.add_argument("--model", default=DEFAULT_MODEL)
    ap.add_argument("--speaker", default=DEFAULT_SPEAKER)
    ap.add_argument("--pace", type=float, default=DEFAULT_PACE)
    args = ap.parse_args()

    menu = eval_data_js()
    manifest = load_manifest()
    recipes = [r for r in menu["recipes"] if not args.recipe or r["id"] == args.recipe]
    if not recipes:
        sys.exit(f"No recipe with id {args.recipe!r}")

    todo = []
    for r in recipes:
        have = manifest.get(r["id"], {})
        for key, text in clips_for(r):
            h = text_hash(text, args.model, args.speaker, args.pace)
            path = os.path.join(AUDIO_DIR, r["id"], f"{key}.mp3")
            if args.force or have.get(key) != h or not os.path.exists(path):
                todo.append((r["id"], key, text, h, path))

    total_chars = sum(len(t[2]) for t in todo)
    print(f"{len(todo)} clips to generate, {total_chars} characters, model={args.model} speaker={args.speaker} pace={args.pace}")
    if args.dry_run:
        for rid, key, text, _, _ in todo:
            print(f"  {rid}/{key}: {text[:60]}{'…' if len(text) > 60 else ''}")
        return
    if not todo:
        print("Nothing to do — audio is up to date.")
        return

    key = get_key()
    for n, (rid, ckey, text, h, path) in enumerate(todo, 1):
        print(f"[{n}/{len(todo)}] {rid}/{ckey}  ({len(text)} chars)")
        audio = synthesize(text, key, args.model, args.speaker, args.pace)
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "wb") as f:
            f.write(audio)
        manifest.setdefault(rid, {})[ckey] = h
        save_manifest(manifest)          # save after every clip so a crash loses nothing
        time.sleep(0.3)                  # be polite to the rate limit

    # drop manifest entries whose text no longer exists
    valid = {r["id"]: {k for k, _ in clips_for(r)} for r in menu["recipes"]}
    for rid in list(manifest):
        if rid not in valid:
            del manifest[rid]; continue
        for k in list(manifest[rid]):
            if k not in valid[rid]:
                del manifest[rid][k]
    save_manifest(manifest)
    size = sum(os.path.getsize(os.path.join(dp, f)) for dp, _, fs in os.walk(AUDIO_DIR) for f in fs)
    print(f"Done. audio/ is now {size / 1e6:.1f} MB.")


if __name__ == "__main__":
    main()
